"""Added polyline, removed redundant columns from crawl

Revision ID: bb41dd6edbcc
Revises: 68a337a15b9c
Create Date: 2020-04-30 13:16:53.750656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb41dd6edbcc'
down_revision = '68a337a15b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('polyline_string', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'polyline_string')
    # ### end Alembic commands ###
