"""map Bar_Masterlist using reflect, added Crawl Object

Revision ID: f0328f3db62f
Revises: cf096776944a
Create Date: 2020-04-19 16:29:13.438964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0328f3db62f'
down_revision = 'cf096776944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('bar_1', sa.Integer(), nullable=True),
    sa.Column('bar_2', sa.Integer(), nullable=True),
    sa.Column('bar_3', sa.Integer(), nullable=True),
    sa.Column('bar_4', sa.Integer(), nullable=True),
    sa.Column('bar_5', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['bar_1'], ['Bar_MasterList.bar_id'], ),
    sa.ForeignKeyConstraint(['bar_2'], ['Bar_MasterList.bar_id'], ),
    sa.ForeignKeyConstraint(['bar_3'], ['Bar_MasterList.bar_id'], ),
    sa.ForeignKeyConstraint(['bar_4'], ['Bar_MasterList.bar_id'], ),
    sa.ForeignKeyConstraint(['bar_5'], ['Bar_MasterList.bar_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_timestamp'), 'crawl', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_timestamp'), table_name='crawl')
    op.drop_table('crawl')
    # ### end Alembic commands ###
