"""Added date column to crawl

Revision ID: f90f3d0df6b7
Revises: bb41dd6edbcc
Create Date: 2020-05-03 20:08:26.292480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90f3d0df6b7'
down_revision = 'bb41dd6edbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl', 'date')
    # ### end Alembic commands ###
